### ISSUE TITLE
The experiment went wrong！！help!

### ISSUE THREAD

**Issue by AHPUymhd** [PJLab-ADG/DiLu#12]
Dear author, I ran your code and then ran into an error when storing the update experience for the second time, what is the reason?
The following error message is displayed.
==========Simulation 2 Done==========
Moviepy - Building video C:\Users\X\Desktop\DiLu-main\results\highway_2-episode-0.mp4.
Moviepy - Writing video C:\Users\X\Desktop\DiLu-main\results\highway_2-episode-0.mp4

Traceback (most recent call last):
Moviepy - Done !
Moviepy - video ready C:\Users\X\Desktop\DiLu-main\results\highway_2-episode-0.mp4
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\openai\openai_object.py", line 59, in __getattr__
    return self[k]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\X\Desktop\DiLu-main\run_dilu.py", line 121, in <module>
    fewshot_results = agent_memory.retriveMemory(
  File "C:\Users\X\Desktop\DiLu-main\dilu\driver_agent\vectorStore.py", line 43, in retriveMemory
    similarity_results = self.scenario_memory.similarity_search_with_score(
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\langchain\vectorstores\chroma.py", line 432, in similarity_search_with_score
    query_embedding = self._embedding_function.embed_query(query)
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\langchain\embeddings\openai.py", line 578, in embed_query
    return self.embed_documents([text])[0]
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\langchain\embeddings\openai.py", line 549, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\langchain\embeddings\openai.py", line 425, in _get_len_safe_embeddings
    response = embed_with_retry(
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\langchain\embeddings\openai.py", line 114, in embed_with_retry
    return _embed_with_retry(**kwargs)
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "D:\ProgramData\anaconda3\envs\dilu\lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
  File "D:\ProgramData\anaconda3\envs\dilu\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\langchain\embeddings\openai.py", line 111, in _embed_with_retry
    response = embeddings.client.create(**kwargs)
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\openai\api_resources\embedding.py", line 38, in create
    for data in response.data:
  File "D:\ProgramData\anaconda3\envs\dilu\lib\site-packages\openai\openai_object.py", line 61, in __getattr__
    raise AttributeError(*err.args)
AttributeError: data

Process finished with exit code 1
@zijinoier

**Comment by zijinoier** [comment]
It seems that the error is not related to our code but might be due to an issue with the `openai` or `langchain` library. 
You might want to check if your API keys are set correctly and if the version of the openai and langchain libraries you are using are compatible. 

If the problem persists, you may want to reach out to the support teams of these libraries for further assistance.
